[tool.black]
line-length = 88
target-version = ['py311']
skip-string-normalization = true

[tool.ruff]
line-length = 88
target-version = "py311"
src = ["."]
fix = true

[tool.ruff.lint]
select = ["E", "F", "W", "I", "C", "N", "B"]
ignore = ["E501", "F841", "N806", "C901"]

[tool.isort]
profile = "black"
line_length = 88
