# Generated by Django 5.2.5 on 2025-08-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idioma",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "tipo_contenido",
                    models.CharField(
                        choices=[
                            ("crossword", "Crossword"),
                            ("wordsearch", "Wordsearch"),
                            ("coloring_kids", "Coloring Kids"),
                            ("coloring_adults", "Coloring Adults"),
                            ("calligraphy", "Calligraphy"),
                            ("sudoku", "Sudoku"),
                            ("mandala", "Mandala"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="lexicon_cat_slug_fce4d4_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Palabra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("dificultad", models.PositiveSmallIntegerField(default=1)),
                ("tags", models.JSONField(blank=True, null=True)),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True, related_name="palabras", to="lexicon.categoria"
                    ),
                ),
                (
                    "idioma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lexicon.idioma"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListaPalabras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True, related_name="listas", to="lexicon.categoria"
                    ),
                ),
                (
                    "idioma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lexicon.idioma"
                    ),
                ),
                (
                    "palabras",
                    models.ManyToManyField(
                        blank=True, related_name="listas", to="lexicon.palabra"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="palabra",
            index=models.Index(
                fields=["texto", "idioma"], name="lexicon_pal_texto_fb8373_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="palabra",
            constraint=models.UniqueConstraint(
                fields=("texto", "idioma"), name="unique_texto_idioma"
            ),
        ),
    ]
