# Generated by Django 5.2.5 on 2025-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('word', models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    'language',
                    models.CharField(
                        choices=[
                            ('es', 'Spanish'),
                            ('en', 'English'),
                            ('fr', 'French'),
                            ('de', 'German'),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
