# Generated by Django 5.2.5 on 2025-08-25 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaJuego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("crossword", "Crossword"),
                            ("wordsearch", "Wordsearch"),
                            ("coloring_kids", "Coloring Kids"),
                            ("coloring_adults", "Coloring Adults"),
                            ("calligraphy", "Calligraphy"),
                            ("sudoku", "Sudoku"),
                            ("mandala", "Mandala"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("parametros_schema", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="JuegoGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("crossword", "Crossword"),
                            ("wordsearch", "Wordsearch"),
                            ("coloring_kids", "Coloring Kids"),
                            ("coloring_adults", "Coloring Adults"),
                            ("calligraphy", "Calligraphy"),
                            ("sudoku", "Sudoku"),
                            ("mandala", "Mandala"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parametros", models.JSONField()),
                ("resultado", models.JSONField(blank=True, null=True)),
                ("seed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("png", "PNG"), ("svg", "SVG")],
                        max_length=3,
                    ),
                ),
                ("archivo", models.FileField(upload_to="exports/%Y/%m/%d")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "juego",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exportaciones",
                        to="puzzles.juegogenerado",
                    ),
                ),
            ],
        ),
    ]
