# Generated by Django 5.0 on 2025-08-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportacion",
            name="formato",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("png", "PNG"),
                    ("svg", "SVG"),
                    ("zip", "ZIP"),
                ],
                max_length=3,
            ),
        ),
    ]
